# Site settings
contact: george.lele-x.sun@gmail.com
company_name: Sun Websites
company_website: https://www.sunwebsites.org
personal_website: http://www.mrsunny.tech
template_readme: https://github.com/mrsunny0/template-gh-pages/blob/gh-pages/README.md
template_generator: https://github.com/mrsunny0/generator-gls-website

# Front page settings
username: George Sun
title: TITLE
header: HEADER
description: DESCRIPTION
gh_page: https://github.com/mrsunny0/template-gh-pages
background: 
  video: assets/vid/air_balloons.mp4
  image: assets/img/1000.png 
  color: #1a222c 

# Google-analytics
google-analytics:
  id: "UA-161447266-4"

exclude: ['package.json', 'src' , 'node_modules']